packages:
  - apps/*
  - examples/*
  - packages/*

catalog:
  '@mdx-js/loader': 3.1.1
  '@mdx-js/react': 3.1.1
  '@next/mdx': 16.1.6
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/typography': 0.5.19
  '@types/mdx': 2.0.13
  '@types/node': 25.2.0
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  arktype: 2.1.29
  geist: 1.5.1
  next: 16.1.6
  prettier: 3.8.1
  react: 19.2.4
  react-aria-components: 1.14.0
  react-dom: 19.2.4
  restyle: 3.4.2
  tailwindcss: 4.1.18
  tm-grammars: 1.30.3
  tm-themes: 1.11.0
  ts-morph: 27.0.2
  typescript: 5.9.3
  unified: 11.0.5
  valibot: 1.2.0
  vite: 7.3.1
  zod: 4.3.6

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
