packages:
  - 'apps/*'
  - 'examples/*'
  - 'packages/*'

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.3.0
  '@types/mdx': 2.0.13
  '@types/react': 19.1.1
  '@types/react-dom': 19.1.2
  'next': 15.3.0
  'react': 19.1.0
  'react-dom': 19.1.0
  'restyle': 3.4.2
  'ts-morph': 25.0.1
  'valibot': 1.0.0
  'zod': 3.24.3
