packages:
  - apps/*
  - examples/*
  - packages/*

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.4.4
  '@types/hast': 3.0.4
  '@types/mdx': 2.0.13
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  geist: 1.4.2
  next: 15.4.7
  react: 19.1.0
  react-dom: 19.1.0
  restyle: 3.4.2
  tm-grammars: 1.24.0
  tm-themes: 1.10.7
  ts-morph: 26.0.0
  typescript: 5.8.3
  unified: 11.0.5
  valibot: 1.1.0
  zod: 4.0.9

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
