packages:
  - apps/*
  - examples/*
  - packages/*

catalog:
  '@mdx-js/loader': 3.1.1
  '@mdx-js/react': 3.1.1
  '@next/mdx': 15.5.5
  '@tailwindcss/postcss': 4.1.14
  '@tailwindcss/typography': 0.5.19
  '@types/hast': 3.0.4
  '@types/mdx': 2.0.13
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  arktype: 2.1.25
  geist: 1.5.1
  next: 15.5.5
  prettier: 3.6.2
  react: 19.2.0
  react-aria-components: 1.13.0
  react-dom: 19.2.0
  restyle: 3.4.2
  tailwindcss: 4.1.14
  tm-grammars: 1.24.22
  tm-themes: 1.10.11
  ts-morph: 27.0.2
  typescript: 5.9.3
  unified: 11.0.5
  valibot: 1.1.0
  zod: 4.1.12

catalogMode: prefer

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
