packages:
  - apps/*
  - examples/*
  - packages/*

catalog:
  '@mdx-js/loader': 3.1.0
  '@mdx-js/react': 3.1.0
  '@next/mdx': 15.3.3
  '@types/hast': 3.0.4
  '@types/mdx': 2.0.13
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  next: 15.3.3
  react: 19.1.0
  react-dom: 19.1.0
  restyle: 3.4.2
  ts-morph: 26.0.0
  unified: 11.0.5
  valibot: 1.1.0
  zod: 3.25.64
