// prettier-ignore
export const grammarLoaders: Record<string, () => Promise<{ default: any }>> = {
  'source.css': () => import('./css.ts'),
  'text.html.basic': () => import('./html.ts'),
  'source.json': () => import('./json.ts'),
  'source.mdx': () => import('./mdx.ts'),
  'source.shell': () => import('./shellscript.ts'),
  'source.tsx': () => import('./tsx.ts')
}

// prettier-ignore
export const grammarRedirects = {
  'source.ts': 'source.tsx',
  'source.js.jsx': 'source.tsx',
  'text.html.markdown': 'source.mdx'
}

// prettier-ignore
export const grammars = {
  'source.abap': ['abap'],
  'source.actionscript.3': ['actionscript-3'],
  'source.ada': ['ada'],
  'text.html.derivative.ng': ['angular-html'],
  'source.ts.ng': ['angular-ts'],
  'source.apacheconf': ['apache'],
  'source.apex': ['apex'],
  'source.apl': ['apl'],
  'source.applescript': ['applescript'],
  'source.ara': ['ara'],
  'text.asciidoc': ['asciidoc', 'adoc'],
  'source.asm.x86_64': ['asm'],
  'source.astro': ['astro'],
  'source.awk': ['awk'],
  'source.ballerina': ['ballerina'],
  'source.batchfile': ['bat', 'batch'],
  'text.beancount': ['beancount'],
  'source.berry': ['berry', 'be'],
  'text.bibtex': ['bibtex'],
  'source.bicep': ['bicep'],
  'text.html.php.blade': ['blade'],
  'source.bsl': ['bsl', '1c'],
  'source.c': ['c'],
  'source.cadence': ['cadence', 'cdc'],
  'source.cairo0': ['cairo'],
  'source.clar': ['clarity'],
  'source.clojure': ['clojure', 'clj'],
  'source.cmake': ['cmake'],
  'source.cobol': ['cobol'],
  'text.codeowners': ['codeowners'],
  'source.ql': ['codeql', 'ql'],
  'source.coffee': ['coffee', 'coffeescript'],
  'source.commonlisp': ['common-lisp', 'lisp'],
  'source.coq': ['coq'],
  'source.cpp': ['cpp', 'c++'],
  'source.crystal': ['crystal'],
  'source.cs': ['csharp', 'c#', 'cs'],
  'source.css': ['css'],
  'text.csv': ['csv'],
  'source.cue': ['cue'],
  'source.cypher': ['cypher', 'cql'],
  'source.d': ['d'],
  'source.dart': ['dart'],
  'source.dax': ['dax'],
  'source.desktop': ['desktop'],
  'source.diff': ['diff'],
  'source.dockerfile': ['docker', 'dockerfile'],
  'source.dotenv': ['dotenv'],
  'source.dm': ['dream-maker'],
  'text.html.edge': ['edge'],
  'source.elixir': ['elixir'],
  'source.elm': ['elm'],
  'source.emacs.lisp': ['emacs-lisp', 'elisp'],
  'text.html.erb': ['erb'],
  'source.erlang': ['erlang', 'erl'],
  'source.fnl': ['fennel'],
  'source.fish': ['fish'],
  'source.ftl': ['fluent', 'ftl'],
  'source.fortran.fixed': ['fortran-fixed-form', 'f', 'for', 'f77'],
  'source.fortran.free': ['fortran-free-form', 'f90', 'f95', 'f03', 'f08', 'f18'],
  'source.fsharp': ['fsharp', 'f#', 'fs'],
  'source.gdresource': ['gdresource'],
  'source.gdscript': ['gdscript'],
  'source.gdshader': ['gdshader'],
  'source.genie': ['genie'],
  'text.gherkin.feature': ['gherkin'],
  'text.git-commit': ['git-commit'],
  'text.git-rebase': ['git-rebase'],
  'source.gleam': ['gleam'],
  'source.gjs': ['glimmer-js', 'gjs'],
  'source.gts': ['glimmer-ts', 'gts'],
  'source.glsl': ['glsl'],
  'source.gnuplot': ['gnuplot'],
  'source.go': ['go'],
  'source.graphql': ['graphql', 'gql'],
  'source.groovy': ['groovy'],
  'source.hack': ['hack'],
  'text.haml': ['haml'],
  'text.html.handlebars': ['handlebars', 'hbs'],
  'source.haskell': ['haskell', 'hs'],
  'source.hx': ['haxe'],
  'source.hcl': ['hcl'],
  'source.hjson': ['hjson'],
  'source.hlsl': ['hlsl'],
  'text.html.basic': ['html'],
  'text.html.derivative': ['html-derivative'],
  'source.http': ['http'],
  'source.hxml': ['hxml'],
  'source.hy': ['hy'],
  'source.imba': ['imba'],
  'source.ini': ['ini', 'properties'],
  'source.java': ['java'],
  'source.ts': ['javascript', 'js', 'typescript', 'ts'],
  'source.jinja': ['jinja'],
  'source.jison': ['jison'],
  'source.json': ['json'],
  'source.json5': ['json5'],
  'source.json.comments': ['jsonc'],
  'source.json.lines': ['jsonl'],
  'source.jsonnet': ['jsonnet'],
  'source.jssm': ['jssm', 'fsl'],
  'source.js.jsx': ['jsx'],
  'source.julia': ['julia', 'jl'],
  'source.kotlin': ['kotlin', 'kt', 'kts'],
  'source.kusto': ['kusto', 'kql'],
  'text.tex.latex': ['latex'],
  'source.lean4': ['lean', 'lean4'],
  'source.css.less': ['less'],
  'text.html.liquid': ['liquid'],
  'source.llvm': ['llvm'],
  'text.log': ['log'],
  'source.logo': ['logo'],
  'source.lua': ['lua'],
  'source.luau': ['luau'],
  'source.makefile': ['make', 'makefile'],
  'text.html.markdown': ['markdown', 'md'],
  'text.marko': ['marko'],
  'source.matlab': ['matlab'],
  'text.markdown.mdc.standalone': ['mdc'],
  'source.mdx': ['mdx'],
  'markdown.mermaid.codeblock': ['mermaid', 'mmd'],
  'source.mips': ['mipsasm', 'mips'],
  'source.mojo': ['mojo'],
  'source.move': ['move'],
  'source.narrat': ['narrat', 'nar'],
  'source.nextflow': ['nextflow', 'nf'],
  'source.nginx': ['nginx'],
  'source.nim': ['nim'],
  'source.nix': ['nix'],
  'source.nushell': ['nushell', 'nu'],
  'source.objc': ['objective-c', 'objc'],
  'source.objcpp': ['objective-cpp'],
  'source.ocaml': ['ocaml'],
  'source.pascal': ['pascal'],
  'source.perl': ['perl'],
  'source.php': ['php'],
  'source.plsql.oracle': ['plsql'],
  'source.po': ['po', 'pot', 'potx'],
  'source.polar': ['polar'],
  'source.css.postcss': ['postcss'],
  'source.powerquery': ['powerquery'],
  'source.powershell': ['powershell', 'ps', 'ps1'],
  'source.prisma': ['prisma'],
  'source.prolog': ['prolog'],
  'source.proto': ['proto', 'protobuf'],
  'text.pug': ['pug', 'jade'],
  'source.puppet': ['puppet'],
  'source.purescript': ['purescript'],
  'source.python': ['python', 'py'],
  'source.qml': ['qml'],
  'source.qmldir': ['qmldir'],
  'source.qss': ['qss'],
  'source.r': ['r'],
  'source.racket': ['racket'],
  'source.perl.6': ['raku', 'perl6'],
  'text.aspnetcorerazor': ['razor'],
  'source.reg': ['reg'],
  'source.regexp.python': ['regexp', 'regex'],
  'source.rel': ['rel'],
  'source.riscv': ['riscv'],
  'source.rst': ['rst'],
  'source.ruby': ['ruby', 'rb'],
  'source.rust': ['rust', 'rs'],
  'source.sas': ['sas'],
  'source.sass': ['sass'],
  'source.scala': ['scala'],
  'source.scheme': ['scheme'],
  'source.css.scss': ['scss'],
  'source.sdbl': ['sdbl', '1c-query'],
  'source.shaderlab': ['shaderlab', 'shader'],
  'source.shell': ['shellscript', 'bash', 'sh', 'shell', 'zsh'],
  'text.shell-session': ['shellsession', 'console'],
  'source.smalltalk': ['smalltalk'],
  'source.solidity': ['solidity'],
  'text.html.soy': ['soy', 'closure-templates'],
  'source.sparql': ['sparql'],
  'source.splunk_search': ['splunk', 'spl'],
  'source.sql': ['sql'],
  'source.ssh-config': ['ssh-config'],
  'source.stata': ['stata'],
  'source.stylus': ['stylus', 'styl'],
  'source.svelte': ['svelte'],
  'source.swift': ['swift'],
  'source.systemverilog': ['system-verilog'],
  'source.systemd': ['systemd'],
  'source.talon': ['talonscript', 'talon'],
  'source.tasl': ['tasl'],
  'source.tcl': ['tcl'],
  'source.templ': ['templ'],
  'source.hcl.terraform': ['terraform', 'tf', 'tfvars'],
  'text.tex': ['tex'],
  'source.toml': ['toml'],
  'source.ts.tags': ['ts-tags', 'lit'],
  'text.tsv': ['tsv'],
  'source.tsx': ['tsx'],
  'source.turtle': ['turtle'],
  'text.html.twig': ['twig'],
  'source.tsp': ['typespec', 'tsp'],
  'source.typst': ['typst', 'typ'],
  'source.v': ['v'],
  'source.vala': ['vala'],
  'source.asp.vb.net': ['vb', 'cmd'],
  'source.verilog': ['verilog'],
  'source.vhdl': ['vhdl'],
  'source.viml': ['viml', 'vim', 'vimscript'],
  'source.vue': ['vue'],
  'text.html.vue-html': ['vue-html'],
  'source.vue-vine': ['vue-vine'],
  'source.vyper': ['vyper', 'vy'],
  'source.wat': ['wasm'],
  'source.wenyan': ['wenyan', '文言'],
  'source.wgsl': ['wgsl'],
  'source.wikitext': ['wikitext', 'mediawiki', 'wiki'],
  'source.wit': ['wit'],
  'source.wolfram': ['wolfram', 'wl'],
  'text.xml': ['xml'],
  'text.xml.xsl': ['xsl'],
  'source.yaml': ['yaml', 'yml'],
  'source.zenscript': ['zenscript'],
  'source.zig': ['zig']
} as const

export type Grammars = typeof grammars

export type ScopeName = keyof Grammars

export type Languages = Grammars[ScopeName][number]

// prettier-ignore
export const themes = ['andromeeda', 'aurora-x', 'ayu-dark', 'catppuccin-frappe', 'catppuccin-latte', 'catppuccin-macchiato', 'catppuccin-mocha', 'dark-plus', 'dracula', 'dracula-soft', 'everforest-dark', 'everforest-light', 'github-dark', 'github-dark-default', 'github-dark-dimmed', 'github-dark-high-contrast', 'github-light', 'github-light-default', 'github-light-high-contrast', 'gruvbox-dark-hard', 'gruvbox-dark-medium', 'gruvbox-dark-soft', 'gruvbox-light-hard', 'gruvbox-light-medium', 'gruvbox-light-soft', 'houston', 'kanagawa-dragon', 'kanagawa-lotus', 'kanagawa-wave', 'laserwave', 'light-plus', 'material-theme', 'material-theme-darker', 'material-theme-lighter', 'material-theme-ocean', 'material-theme-palenight', 'min-dark', 'min-light', 'monokai', 'night-owl', 'nord', 'one-dark-pro', 'one-light', 'plastic', 'poimandres', 'red', 'rose-pine', 'rose-pine-dawn', 'rose-pine-moon', 'slack-dark', 'slack-ochin', 'snazzy-light', 'solarized-dark', 'solarized-light', 'synthwave-84', 'tokyo-night', 'vesper', 'vitesse-black', 'vitesse-dark', 'vitesse-light'] as const

export type Themes = (typeof themes)[number]
