/* This file was automatically generated by the `mdxts` package. */
import { createCollection } from 'mdxts/core'

createCollection.setImportMap(
  `ts:@/components/**/{index,*.examples}.{ts,tsx}`,
  (slug) => import(`@/components/${slug}.ts`),
  `mdx:@/components/**/README.mdx`,
  (slug) => import(`@/components/${slug}.mdx`)
)

export * from 'mdxts/core'
