export const DEFAULT_WORKSPACE_CHANGE_TOKEN_TTL_MS = 1_000
export const DEFAULT_WORKSPACE_CHANGED_PATHS_TTL_MS = 1_000
export const DEFAULT_INVALIDATED_PATH_TTL_MS = 1_000
export const DEFAULT_CACHE_METRICS_TOP_KEYS_LIMIT = 10
export const DEFAULT_CACHE_METRICS_TOP_KEYS_TRACKING_LIMIT = 250
export const DEFAULT_CACHE_METRICS_TOP_KEYS_LOG_INTERVAL = 25
export const DIRECTORY_SNAPSHOT_DEP_INDEX_PREFIX = 'const:dir-snapshot-path:'
