name: Preview Packages

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  issues: read

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    if: github.event.action != 'closed' && github.event.pull_request.head.repo.fork == false && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: preview-branch
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false
          path: pr

      - name: Checkout trusted workflow code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
          persist-credentials: false
          path: trusted

      - name: Setup Node and pnpm
        uses: ./trusted/.github/actions/setup-node-pnpm

      - name: Install dependencies
        working-directory: pr
        run: pnpm install

      - name: Build
        working-directory: pr
        run: pnpm build --filter=packages/*

      - name: Create preview branch assets
        working-directory: pr
        run: node ../trusted/.github/scripts/package-preview/create.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload manifest for comment step
        uses: actions/upload-artifact@v4
        with:
          name: preview-manifest
          path: pr/previews/manifest.json
          if-no-files-found: ignore

  comment:
    needs: build-and-publish
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' && github.event.pull_request.head.repo.fork == false && github.event.pull_request.draft == false
    concurrency:
      group: preview-branch
      cancel-in-progress: false
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false
          path: pr

      - name: Checkout trusted workflow code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
          persist-credentials: false
          path: trusted

      - name: Setup Node and pnpm
        uses: ./trusted/.github/actions/setup-node-pnpm

      - name: Download manifest
        id: download
        uses: actions/download-artifact@v4
        with:
          name: preview-manifest
          path: pr/previews
        continue-on-error: true

      - name: Install dependencies
        working-directory: trusted
        run: pnpm install --frozen-lockfile=false

      - name: Post sticky comment with install commands
        if: steps.download.outcome == 'success'
        working-directory: pr
        run: node ../trusted/.github/scripts/package-preview/comment.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

  cleanup:
    if: github.event.action == 'closed' && github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    concurrency:
      group: preview-branch
      cancel-in-progress: false
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout trusted workflow code (base branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 1
          persist-credentials: false
          path: trusted

      - name: Setup Node and pnpm
        uses: ./trusted/.github/actions/setup-node-pnpm

      - name: Remove preview branch assets for this PR
        working-directory: trusted
        run: node .github/scripts/package-preview/cleanup.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
